#!/usr/bin/env sh

# Library funcs for scripts.
# Borrowed from git-sh-setup

eval "$(echo "$OPTIONS_SPEC" | git rev-parse --parseopt -- "$@" || echo exit $?)"

say () {
	printf '%s\n' "$*"
}

die () {
	die_with_status 1 "$@"
}

die_with_status () {
	status=$1
	shift
	printf >&2 '%s\n' "$*"
	exit "$status"
}

usage() {
    "$0" -h
    exit 1
}
