#!/usr/bin/env sh

[ -z "$(command -v git)" ] && return

docker-install-completion() {
    if [ -d /usr/local/etc/bash_completion.d ] && [ -d /Applications/Docker.app/Contents/Resources/etc/ ]; then 
        ln -fs /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion          /usr/local/etc/bash_completion.d/docker.bash-completion
        ln -fs /Applications/Docker.app/Contents/Resources/etc/docker-machine.bash-completion  /usr/local/etc/bash_completion.d/docker-machine.bash-completion
        ln -fs /Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion  /usr/local/etc/bash_completion.d/docker-compose.bash-completion
    fi
}
