#!/usr/bin/env sh

[ -z "$(command -v git)" ] && return

alias git-log='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'
alias git-done="git commit -am '$1' && git push"

git-whichbranch() {
    if [ -n "$(command -v git)" ]; then
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
    else
        echo ""
    fi
}