#!/usr/bin/env sh

( [ "$(uname -s)" != "Darwin" ] || [ -z "$(command -v brew)" ] ) && return

brewfile-install() {
    brew update
    brew bundle install -v --file $DOTPATH/homebrew/brewfile
}

brewfile-dump() {
    brew bundle dump --force --file $DOTPATH/homebrew/brewfile
}

homebrew-install() {
    if [ "$(uname -s)" == "Darwin" ]; then
        if [ -z "$(command -v brew)" ]; then
            /usr/bin/env ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
    fi
}
