#!/usr/bin/env sh

( [ "$(uname -s)" != "Darwin" ] || [ -z "$(command -v brew)" ] ) && return

brewfile-install() (
    cd $DOTPATH/homebrew
    brew update
    brew bundle install -v
)

brewfile-dump() (
    cd $DOTPATH/homebrew
    brew bundle dump --force
)

homebrew-install() {
    if [ "$(uname -s)" == "Darwin" ]; then
        if [ -z "$(command -v brew)" ]; then
            /usr/bin/env ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
    fi
}
