#!/usr/bin/env sh

[ -z "$(command -v code)" ] && return

vscode-ext-install() {
    cat $DOTPATH/vscode/extensions | xargs -L 1 echo code --install-extension | sh
}

vscode-ext-dump() {
    code --list-extensions > $DOTPATH/vscode/extensions
}

vscode-settings-install() {
    if [ "$(uname -s)" == "Darwin" ]; then
        cp "$DOTPATH/vscode/settings.json" "$HOME/Library/Application Support/Code/User/settings.json"
    elif [ "$(uname -s)" == "Linux" ]; then
        cp "$DOTPATH/vscode/settings.json" "$HOME/.config/Code/User/settings.json"
    fi
}

vscode-settings-dump() {
    if [ "$(uname -s)" == "Darwin" ]; then
        cp "$HOME/Library/Application Support/Code/User/settings.json" "$DOTPATH/vscode/settings.json"
    elif [ "$(uname -s)" == "Linux" ]; then
        cp "$HOME/.config/Code/User/settings.json" "$DOTPATH/vscode/settings.json"
    fi
}
