#!/usr/bin/env sh

[ -z "$(command -v code)" ] && return

vscode-ext-install() {
    cat $DOTPATH/vscode/extensions | xargs -L 1 echo code --install-extension | sh
}

vscode-ext-dump() {
    code --list-extensions > $DOTPATH/vscode/extensions
}