steps:
  - id: github-ssh
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    dir: /root/.ssh
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access latest --secret=${_GHE_KEY_SECRET} > id_rsa
        gcloud secrets versions access latest --secret=${_GHE_KNOWNHOST_SECRET} > known_hosts
        chmod 400 id_rsa
        cat <<EOF >config
        Hostname github.platforms.engineering
        IdentityFile  /root/.ssh/id_rsa
        EOF
  - id: vault-creds
    name: ${_BUILDER_IMAGE}
    secretEnv: ["VAULT_SECRET"]
    entrypoint: bash
    args:
      - -c
      - curl https://vault.agro.services:443/v1/auth/approle/login --data "$$VAULT_SECRET" | jq -r -j .auth.client_token > .vault-token
  - name: ${_BUILDER_IMAGE}
    id: integration-tests
    entrypoint: bash
    args:
    - -c
    - |
      set -o errexit -o pipefail

      # needed to make tests/integration/testing.mk happy
      git config --global user.email "foo@foo.com"
      git config --global user.name "Foo"
      git init
      git add .
      git commit -m WIP
      git tag -a WIP -m WIP

      export HOST_WORKDIR=/workspace
      export HOST_VAULT_TOKEN_FILE="/workspace/.vault-token"
      export HOST_GOCACHE=/workspace/.cache/go
      export HOST_GOMODCACHE=/workspace/.cache/mod
      export HOST_SSH_CONFIG="$(docker volume inspect --format '{{ .Mountpoint }}' ssh)"
      export COMPOSE_PROJECT_NAME=genomics

      export GOMODCACHE=/workspace/.cache/mod
      go mod download

      make -C '${_CURRENT_DIR}' test-integration-ci ARGS='${_ARGS}'
substitutions:
  _GHE_KEY_SECRET: cloudbuild-master-rsa
  _GHE_KNOWNHOST_SECRET: ghe-known_host
  _BUILDER_IMAGE: us-central1-docker.pkg.dev/product360-ops/build/golang:4-build5
availableSecrets:
  secretManager:
  - versionName: projects/product360-nonprod/secrets/vapprole-product360-genomics-engineers-integration-tests/versions/latest
    env: 'VAULT_SECRET'
options:
  machineType: "N1_HIGHCPU_8"
  volumes:
    - name: ssh
      path: /root/.ssh
tags: ["integration-tests", "genomics"]
timeout: "3600s"
